(()=>{function _(e,n){let t=e.indexOf(n);return t<0?[e]:[e.slice(0,t),e.slice(t+n.length)]}async function*u(e){let n=e.body.getReader(),t=new TextDecoder("utf-8"),o="",s=1e3;for(;;){let{done:d,value:c}=await n.read();if(d||s--<=0)break;o+=t.decode(c,{stream:!d});let r=null;for(;o&&o.includes(`
`);)if([r,o]=_(o,`
`),r){let[l,i]=_(r,":");yield{cmd:l.trim(),data:i.trim()}}}return!0}var f={props:{exporting:{type:Boolean,default:!1},files:{type:Array,default:()=>[]}},data(){return{newExport:null}},computed:{sortedFiles(){return this.files.sort((e,n)=>new Date(n.date)-new Date(e.date))}},methods:{fetch(e,n){n=Object.assign(n||{},{credentials:"same-origin",cache:"no-store",headers:{"x-requested-with":"xmlhttprequest","content-type":"application/json",...n.headers}});let t=this.$api.config;return t.methodOverwrite&&n.method!=="GET"&&n.method!=="POST"&&(n.headers["x-http-method-override"]=n.method,n.method="POST"),n=t.onPrepare(n),fetch([t.endpoint,e].join(t.endpoint.endsWith("/")||e.startsWith("/")?"":"/"),n)},downloadFile(e){let n=this.$api.config,t=`/exports/${e.id}/download`;window.location.href=[n.endpoint,t].join(n.endpoint.endsWith("/")||t.startsWith("/")?"":"/")},deleteFile(e){this.$dialog(`export/${e.id}/delete`)},niceDate(e){return new Date(e).toLocaleString()},niceSize(e){let n=["B","KB","MB","GB","TB","PB","EB","ZB","YB"],t=0;for(;e>=1024;)e/=1024,++t;return`${Math.round(e*100)/100} ${n[t]}`},createExport(){this.$dialog("export/create",({data:e,dialog:n})=>{e.basePath?(this.startExport(e),n.close()):n.error("Please select a base path")})},async startExport({recreateImages:e=!1,basePath:n=void 0}){this.exporting=!0;let t=1/0;this.newExport={id:null,date:null,status:null,size:null,basePath:n};for await(let{cmd:o,data:s}of u(await this.fetch("/exports",{method:"POST",body:JSON.stringify({recreateImages:e,basePath:n})})))o==="id"?this.$set(this.newExport,"id",s):o==="date"?this.$set(this.newExport,"date",s):o==="basepath"?this.$set(this.newExport,"basePath",s):o==="count"?(t=parseInt(s),this.$set(this.newExport,"count",parseInt(s))):o==="progress"?this.$set(this.newExport,"status",parseInt(s)/t):o==="size"&&setTimeout(()=>{this.files.push({id:this.newExport.id,date:this.newExport.date,size:s,basePath:this.newExport.basePath}),this.newExport=null,this.exporting=!1},300)}}},x=function(){var e=this,n=e.$createElement,t=e._self._c||n;return t("k-inside",[t("k-view",[t("k-header",[e._v(`
            Static Export
            `),t("k-button-group",{attrs:{slot:"left"},slot:"left"},[t("k-button",{attrs:{disabled:e.exporting,icon:"download"},on:{click:e.createExport}},[e._v(`
                    Start a new export
                `)])],1)],1),e._v(" "),e.files.length||e.newExport?t("table",{staticClass:"rs-exports"},[t("tr",[t("th",[e._v("Date")]),e._v(" "),t("th",[e._v("Base Path")]),e._v(" "),t("th",[e._v("Size")]),e._v(" "),t("th",{staticClass:"rs-exports__options"})]),e._v(" "),e.newExport?t("tr",[t("td",[e._v(e._s(e.niceDate(e.newExport.date)))]),e._v(" "),t("td",[e._v(e._s(e.newExport.basePath))]),e._v(" "),t("td",[t("k-progress",{attrs:{value:e.newExport.status*100}})],1),e._v(" "),t("td",{staticClass:"rs-exports__options"},[t("k-options-dropdown",{attrs:{options:[{label:"Cancel",icon:"times",action:"cancel"}]}})],1)]):e._e(),e._v(" "),e._l(e.sortedFiles,function(o){return t("tr",{key:o.id},[t("td",[e._v(e._s(e.niceDate(o.date)))]),e._v(" "),t("td",[e._v(e._s(o.basePath))]),e._v(" "),t("td",[e._v(e._s(e.niceSize(o.size)))]),e._v(" "),t("td",{staticClass:"rs-exports__options"},[t("k-options-dropdown",{attrs:{options:[{icon:"download",text:"Download",click:function(){return e.downloadFile(o)}},{icon:"trash",text:"Delete",click:function(){return e.deleteFile(o)}}]}})],1)])})],2):t("k-empty",[e._v(`
            No exports are available yet.
        `)])],1)],1)},v=[],w=void 0,m=void 0,g=void 0,E=!1;function y(e,n,t,o,s,d,c,p,r,l){let i=(typeof t=="function"?t.options:t)||{};return i.__file="style>",i.render||(i.render=e.render,i.staticRenderFns=e.staticRenderFns,i._compiled=!0,s&&(i.functional=!0)),i._scopeId=o,i}var k=y({render:x,staticRenderFns:v},w,f,m,E,g,!1,void 0,void 0,void 0),h=k;panel.plugin("rasteiner/export",{components:{"rs-export-view":h}});})();
